site_name: InfoVote Dashboard

# Repository
repo_name: infovote-io/dashboard
repo_url: https://github.com/infovote-io/dashboard
edit_uri: edit/main/docs/

nav:
  - Home: index.md

# Configuration
theme:
  name: material
  language: pt
  # custom_dir: overrides
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.action.edit
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
    edit: material/pencil
    view: material/eye

markdown_extensions:
  - abbr
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.tasklist  # Lista de tarefas
  - pymdownx.emoji  # Emojis
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - toc:
      permalink: ⚓︎
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - abbreviations.md

extra_css:
  - assets/style.css
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
extra_javascript:
  - assets/style.js
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

extra: # Footer
  version:
    provider: mike

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      enable_creation_date: true
  - mike:
      version_selector: true
  - search:
      lang: pt
  - charts
